---
title: "git_00"
author: "Jaylen Johnson"
date: "Year 2023"
output:
  html_document: default
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
’Twas brillig, and the slithy toves  
      Did gyre and gimble in the wabe:  
All mimsy were the borogoves,  
      And the mome raths outgrabe.  

“Beware the Jabberwock, my son!  
      The jaws that bite, the claws that catch!  
Beware the Jubjub bird, and shun  
      The frumious Bandersnatch!”  
      
## Second Verse
Two roads diverged in a yellow wood,  
And sorry I could not travel both  
And be one traveler, long I stood  
And looked down one as far as I could  
To where it bent in the undergrowth;  

Then took the other, as just as fair,  
And having perhaps the better claim,  
Because it was grassy and wanted wear;  
Though as for that the passing there  
Had worn them really about the same,  

## Third Verse
"The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make  
      The billows smooth and bright —  
And this was odd, because it was  
      The middle of the night.  

The moon was shining sulkily,  
      Because she thought the sun  
Had got no business to be there  
      After the day was done —  
"It's very rude of him," she said,  
      "To come and spoil the fun."  

## Last Verse
So on his Nightmare through the evening fog  

Flits the squab Fiend o'er fen, and lake, and bog;  
Seeks some love-wilder’d maid with sleep oppress’d,  
Alights, and grinning sits upon her breast.

…expanded version, titled The Loves of Plants…  

—Such as of late amid the murky sky  

Was mark’d by Fuseli’s poetic eye;  
Whose daring tints, with Shakspeare’s happiest grace,  
Gave to the airy phantom form and place.—  
Back o'er her pillow sinks her blushing head,  
Her snow-white limbs hang helpless from the bed;  
Her interrupted heart-pulse swims in death.  
